let pContenido = document.querySelector(".section_cpu")

pContenido.innerHTML = 

`
    <h1 class="titContenido">CPU</h1>

    <div class="defini">
    
        <p>CPU son las siglas de Central Processing Unit, lo que traducido significa Unidad Central de Procesamiento. Se trata de uno de los componentes vitales que te vas a encontrar en tu ordenador, tu smartphone o tu tableta o portátil, e incluso en relojes y prácticamente cualquier dispositivo electrónico. Sin él, simplemente no podrían funcionar. <br> <br>A la CPU se la suele llamar coloquialmente como microprocesador o simplemente procesador, y puedes considerarla como el cerebro de cualquier dispositivo. Se encarga de procesar todas las instrucciones del dispositivo, leyendo las órdenes y requisitos del sistema operativo, así como las instrucciones de cada uno de los componentes y las aplicaciones.</p>

    

        <div class="cajonImg">
            <img src="https://4.imimg.com/data4/YD/WW/MY-31969445/brand-new-cpu-sealed-pack.jpg" alt="" class="imgDefin">
        </div>
    </div>

    <h1 class="titCarac">Características</h1>
    <div class="pList">

        <table>
            <tr>
                <td class="subtitTab">Consumo energético</td>
                <td>Es la velocidad que puede desarrollar el CPU, misma que está determinada por la potencia.</td>
            </tr>
            <tr>
                <td class="subtitTab">Número de núcleos</td>
                <td>A mayor cantidad de núcleos, mayor la cantidad de acciones que pueden realizarse en forma simultánea.</td>
            </tr>
            <tr>
                <td class="subtitTab">Memoria caché</td>
                <td>Almacena datos y permite acceder a ellos de manera rápida. La velocidad y capacidad de la memoria caché mejora el desempeño del dispositivo.</td>
            </tr>
            <tr>
                <td class="subtitTab">Número de hilos</td>
                <td>Ayuda al procesador a manejar y ejecutar acciones de forma más eficiente. Divide las tareas o procesos para optimizar los tiempos de espera entre una acción y la otra.</td>
            </tr>
            <tr>
                <td class="subtitTab">Frecuencia de reloj</td>
                <td>Refiere a la velocidad de reloj que tiene el CPU y que determina la cantidad de acciones que puede ejecutar en un período de tiempo.</td>
            </tr>


        </table>
    </div>`;

